name: Whatever

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Running Job 1, Step 1"
      - name: Step 2
        run: echo "Running Job 1, Step 2"
      - name: Step 3
        run: echo "Running Job 1, Step 3"
      - name: Step 4
        run: echo "Running Job 1, Step 4"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Running Job 2, Step 1"
      - name: Step 2
        run: echo "Running Job 2, Step 2"
      - name: Step 3
        run: echo "Running Job 2, Step 3"

  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - name: Step 1
        run: echo "Running Job 3, Step 1"
      - name: Step 2
        run: echo "Running Job 3, Step 2"
      - name: Step 3
        run: echo "Running Job 3, Step 3"
